# Generated by Django 3.2.21 on 2023-10-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_summary_review_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='ceated_by',
            new_name='created_by',
        ),
    ]
